// CLC Main Category
IF(ISNUMBER(SEARCH("CLC",BK:BK)),IF(ISNUMBER(SEARCH(1001,A:A)),"01W Women's Fashion Tops",
IF(ISNUMBER(SEARCH(1003,A:A)),"01X Women's Fashion Bottoms",
IF(ISNUMBER(SEARCH(1004,A:A)),"01W Women's Fashion Tops",
IF(ISNUMBER(SEARCH(1005,A:A)),"01W Women's Fashion Tops",
IF(ISNUMBER(SEARCH(1030,A:A)),"01X Women's Fashion Bottoms",
IF(ISNUMBER(SEARCH(1031,A:A)),"01W Women's Fashion Tops",
IF(ISNUMBER(SEARCH(1032,A:A)),"01S Women's Fleece",
IF(ISNUMBER(SEARCH(1033,A:A)),"01W Women's Fashion Tops",
IF(ISNUMBER(SEARCH(1034,A:A)),"01I Women's Tshirts",
IF(ISNUMBER(SEARCH(1035,A:A)),"01W Women's Fashion Tops",
IF(ISNUMBER(SEARCH(1037,A:A)),"01I Women's Tshirts",
IF(ISNUMBER(SEARCH(1038,A:A)),"01W Women's Fashion Tops",
IF(ISNUMBER(SEARCH(1039,A:A)),"01I Women's Tshirts",
IF(ISNUMBER(SEARCH(1040,A:A)),"01X Women's Fashion Bottoms",
IF(ISNUMBER(SEARCH(1041,A:A)),"01X Women's Fashion Bottoms",
IF(ISNUMBER(SEARCH(1042,A:A)),"01X Women's Fashion Bottoms",
IF(ISNUMBER(SEARCH(1043,A:A)),"01S Women's Fleece",
IF(ISNUMBER(SEARCH(1044,A:A)),"01X Women's Fashion Bottoms",
IF(ISNUMBER(SEARCH(1045,A:A)),"01S Women's Fleece",
IF(ISNUMBER(SEARCH(1048,A:A)),"01T Women's Outerwear",
IF(ISNUMBER(SEARCH(1049,A:A)),"01X Women's Fashion Bottoms",
IF(ISNUMBER(SEARCH(1050,A:A)),"01S Women's Fleece",
IF(ISNUMBER(SEARCH(1051,A:A)),"01X Women's Fashion Bottoms",
"01Y Women's Loungewear, Activewear"))))))))))))))))))))))),"")
