// License Code --> Full Name

=IF(ISNUMBER(SEARCH("BAY01",AG:AG)),"Baylor University",
IF(ISNUMBER(SEARCH("CHI01",AG:AG)),"Chi Omega",
IF(ISNUMBER(SEARCH("COL02",AG:AG)),"Colorado State University",
IF(ISNUMBER(SEARCH("DDD01",AG:AG)),"Delta Delta Delta",
IF(ISNUMBER(SEARCH("IOW01",AG:AG)),"Iowa State University",
IF(ISNUMBER(SEARCH("IOW02",AG:AG)),"University of Iowa",
IF(ISNUMBER(SEARCH("KKG01",AG:AG)),"Kappa Kappa Gamma",
IF(ISNUMBER(SEARCH("KAN02",AG:AG)),"Kansas State University",
IF(ISNUMBER(SEARCH("KAN01",AG:AG)),"University of Kansas",
IF(ISNUMBER(SEARCH("MIS01",AG:AG)),"Missippi State University",
IF(ISNUMBER(SEARCH("MIC02",AG:AG)),"Michigan State University",
IF(ISNUMBER(SEARCH("NCR01",AG:AG)),"North Carolina State University",
IF(ISNUMBER(SEARCH("NCR02",AG:AG)),"University of North Carolina",
IF(ISNUMBER(SEARCH("CAL01",AG:AG)),"University of California, Berkley",
IF(ISNUMBER(SEARCH("COL01",AG:AG)),"University of Colorado",
IF(ISNUMBER(SEARCH("FLO01",AG:AG)),"Florida State University",
IF(ISNUMBER(SEARCH("FLO02",AG:AG)),"University of Florida",
IF(ISNUMBER(SEARCH("FLO03",AG:AG)),"University of Central Florida",
IF(ISNUMBER(SEARCH("GEO01",AG:AG)),"University of Georgia",
IF(ISNUMBER(SEARCH("KEN01",AG:AG)),"University of Kentucky",
IF(ISNUMBER(SEARCH("LOU01",AG:AG)),"Louisiana State University",
IF(ISNUMBER(SEARCH("MAR01",AG:AG)),"University of Maryland",
IF(ISNUMBER(SEARCH("MEM01",AG:AG)),"University of Memphis",
IF(ISNUMBER(SEARCH("MIC01",AG:AG)),"University of Michigan",
IF(ISNUMBER(SEARCH("MIA01",AG:AG)),"University of Miami",
IF(ISNUMBER(SEARCH("SMU01",AG:AG)),"Southern Methodist University",
IF(ISNUMBER(SEARCH("STA01",AG:AG)),"Stanford University",
IF(ISNUMBER(SEARCH("TEX01",AG:AG)),"Texas A&M University",
IF(ISNUMBER(SEARCH("YAL01",AG:AG)),"Yale University",
IF(ISNUMBER(SEARCH("SYR01",AG:AG)),"Syracuse University",
IF(ISNUMBER(SEARCH("NYU01",AG:AG)),"New York University",
IF(ISNUMBER(SEARCH("PRI01",AG:AG)),"Princeton University",
IF(ISNUMBER(SEARCH("HAR01",AG:AG)),"Havard University",
IF(ISNUMBER(SEARCH("TUL01",AG:AG)),"Tulane University",
IF(ISNUMBER(SEARCH("UNB01",AG:AG)),"Unbranded Blue",
IF(ISNUMBER(SEARCH("UNB02",AG:AG)),"Unbranded Purple",
IF(ISNUMBER(SEARCH("UNB03",AG:AG)),"Unbranded Red",
IF(ISNUMBER(SEARCH("UNB04",AG:AG)),"Unbranded Navy",
IF(ISNUMBER(SEARCH("UNB05",AG:AG)),"Unbranded Black",
"MISSING")))))))))))))))))))))))))))))))))))
