// License Code --> Full Name

=IF(ISNUMBER(SEARCH("BAY01",N:N)),"Baylor University",
IF(ISNUMBER(SEARCH("CHI01",N:N)),"Chi Omega",
IF(ISNUMBER(SEARCH("COL02",N:N)),"Colorado State University",
IF(ISNUMBER(SEARCH("DDD01",N:N)),"Delta Delta Delta",
IF(ISNUMBER(SEARCH("IOW01",N:N)),"Iowa State University",
IF(ISNUMBER(SEARCH("IOW02",N:N)),"University of Iowa",
IF(ISNUMBER(SEARCH("KKG01",N:N)),"Kappa Kappa Gamma",
IF(ISNUMBER(SEARCH("KAN02",N:N)),"Kansas State University",
IF(ISNUMBER(SEARCH("KAN01",N:N)),"University of Kansas",
IF(ISNUMBER(SEARCH("MIS01",N:N)),"Missippi State University",
IF(ISNUMBER(SEARCH("MIC02",N:N)),"Michigan State University",
IF(ISNUMBER(SEARCH("NCR01",N:N)),"North Carolina State University",
IF(ISNUMBER(SEARCH("NCR02",N:N)),"University of North Carolina",
IF(ISNUMBER(SEARCH("CAL01",N:N)),"University of California, Berkley",
IF(ISNUMBER(SEARCH("COL01",N:N)),"University of Colorado",
IF(ISNUMBER(SEARCH("FLO01",N:N)),"Florida State University",
IF(ISNUMBER(SEARCH("FLO02",N:N)),"University of Florida",
IF(ISNUMBER(SEARCH("FLO03",N:N)),"University of Central Florida",
IF(ISNUMBER(SEARCH("GEO01",N:N)),"University of Georgia",
IF(ISNUMBER(SEARCH("KEN01",N:N)),"University of Kentucky",
IF(ISNUMBER(SEARCH("LOU01",N:N)),"Louisiana State University",
IF(ISNUMBER(SEARCH("MAR01",N:N)),"University of Maryland",
IF(ISNUMBER(SEARCH("MEM01",N:N)),"University of Memphis",
IF(ISNUMBER(SEARCH("MIC01",N:N)),"University of Michigan",
IF(ISNUMBER(SEARCH("MIA01",N:N)),"University of Miami",
IF(ISNUMBER(SEARCH("UCR02",N:N)),"University of Noth Carolina",
IF(ISNUMBER(SEARCH("MSU01",N:N)),"Southern Methodist University",
IF(ISNUMBER(SEARCH("STA01",N:N)),"Stanford University",
IF(ISNUMBER(SEARCH("TEX01",N:N)),"Texas A&M University",
IF(ISNUMBER(SEARCH("TEX02",N:N)),"University of Texas",
IF(ISNUMBER(SEARCH("YAL01",N:N)),"Yale University",
IF(ISNUMBER(SEARCH("SYR01",N:N)),"Syracuse University",
IF(ISNUMBER(SEARCH("NYU01",N:N)),"New York University",
IF(ISNUMBER(SEARCH("PRI01",N:N)),"Princeton University",
IF(ISNUMBER(SEARCH("HAR01",N:N)),"Havard University",
IF(ISNUMBER(SEARCH("TUL01",N:N)),"Tulane University",
IF(ISNUMBER(SEARCH("UNB01",N:N)),"Unbranded Blue",
IF(ISNUMBER(SEARCH("UNB02",N:N)),"Unbranded Purple",
IF(ISNUMBER(SEARCH("UNB03",N:N)),"Unbranded Red",
IF(ISNUMBER(SEARCH("UNB04",N:N)),"Unbranded Navy",
IF(ISNUMBER(SEARCH("UNB05",N:N)),"Unbranded Black",
"MISSING")))))))))))))))))))))))))))))))))))))