=IF(ISNUMBER(SEARCH(1001,A:A)),"Tops, Shirt, Tank",
IF(ISNUMBER(SEARCH(1003,A:A)),"Bottoms, Short",
IF(ISNUMBER(SEARCH(1004,A:A)),"Top, Tank, Shirt, Rhinestone, Strappy",
IF(ISNUMBER(SEARCH(1005,A:A)),"Top, Shirt, Tank, Sports Bra, Strappy",
IF(ISNUMBER(SEARCH(1006,A:A)),"Sports Bra, Bra, Intimates, Strappy",
IF(ISNUMBER(SEARCH(1007,A:A)),"Sports Bra, Bra, Intimates",
IF(ISNUMBER(SEARCH(1009,A:A)),"Underwear, Thong, Panty, Intimates",
IF(ISNUMBER(SEARCH(1010,A:A)),"Underwear, Boyshort, Briefs, Panty, Intimates",
IF(ISNUMBER(SEARCH(1011,A:A)),"Nukini, Bra, Intimate, Strappy",
IF(ISNUMBER(SEARCH(1012,A:A)),"Nukini, Bra, Intimate, Strappy",
IF(ISNUMBER(SEARCH(1015,A:A)),"Bra, Intimate",
IF(ISNUMBER(SEARCH(1016,A:A)),"Underwear, Thong, Panty, Intimate",
IF(ISNUMBER(SEARCH(1017,A:A)),"Underwear, Boyshort, Panty, Intimate",
IF(ISNUMBER(SEARCH(1018,A:A)),"Nukini, Bra, Intimate,Strappy",
IF(ISNUMBER(SEARCH(1024,A:A)),"Intimate, Bra, Corset, Corselette",
IF(ISNUMBER(SEARCH(1025,A:A)),"Top, Tank, Cropped Tank, Shirt",
IF(ISNUMBER(SEARCH(1030,A:A)),"Bottom, Legging, Pant",
IF(ISNUMBER(SEARCH(1031,A:A)),"Top, Shirt, Sweatshirt",
IF(ISNUMBER(SEARCH(1032,A:A)),"Top, Shirt, Sweatshirt",
IF(ISNUMBER(SEARCH(1033,A:A)),"Top, Shirt, Tank",
IF(ISNUMBER(SEARCH(1034,A:A)),"Top, Shirt, Long Sleeves, Crew",
IF(ISNUMBER(SEARCH(1035,A:A)),"Top, Shirt, Tanks, Yoga",
IF(ISNUMBER(SEARCH(1036,A:A)),"Bottom, Pant, Yoga",
IF(ISNUMBER(SEARCH(1037,A:A)),"Top, Shirt, Tee, V-Neck, Burnout",
IF(ISNUMBER(SEARCH(1038,A:A)),"Top, Shirt, Tank, Burnout",
IF(ISNUMBER(SEARCH(1039,A:A)),"Top, Shirt, Long Sleeve, Crew, Burnout",
IF(ISNUMBER(SEARCH(1040,A:A)),"Bottom, Skort, Short",
IF(ISNUMBER(SEARCH(1041,A:A)),"Bottoms, Short",
IF(ISNUMBER(SEARCH(1042,A:A)),"Bottoms, Skort, Short",
IF(ISNUMBER(SEARCH(1043,A:A)),"Tops, Shirt, Crop Top",
IF(ISNUMBER(SEARCH(1044,A:A)),"Bottoms, Short, Yoga",
IF(ISNUMBER(SEARCH(1045,A:A)),"Hoodie, Sweatshirt, Top, Long Sleeve",
IF(ISNUMBER(SEARCH(1048,A:A)),"Outterwear, Jacket, Cropped, Varsity",
IF(ISNUMBER(SEARCH(1049,A:A)),"Legging, Bottom, Pant",
IF(ISNUMBER(SEARCH(1050,A:A)),"Jogger, Pant, Sweatpant, Lounge, Bottom",
IF(ISNUMBER(SEARCH(1051,A:A)),"Bottom, Skirt",
IF(ISNUMBER(SEARCH(1052,A:A)),"Dress",
IF(ISNUMBER(SEARCH(1055,A:A)),"Sports Bra, Intimate, Bra",
IF(ISNUMBER(SEARCH(1058,A:A)),"Top, Long Sleeve, Shirt, Crew",
IF(ISNUMBER(SEARCH(1064,A:A)),"Dress",
IF(ISNUMBER(SEARCH(1065,A:A)),"Swimwear, One-piece",
IF(ISNUMBER(SEARCH(1066,A:A)),"Top",
IF(ISNUMBER(SEARCH(1067,A:A)),"Top",
IF(ISNUMBER(SEARCH(1068,A:A)),"Swimwear, Bikini, Two-piece",
"Missing"))))))))))))))))))))))))))))))))))))))))))))