// Size --> Size Code

=IF(ISNUMBER(SEARCH("XS",AB:AB)),"XSM",
IF(ISNUMBER(SEARCH("S",AB:AB)),"SML",
IF(ISNUMBER(SEARCH("M",AB:AB)),"MED",
IF(ISNUMBER(SEARCH("XL",AB:AB)),"XLG",
IF(ISNUMBER(SEARCH("32B",AB:AB)),"32B",
IF(ISNUMBER(SEARCH("34A",AB:AB)),"34A",
IF(ISNUMBER(SEARCH("34B",AB:AB)),"34B",
IF(ISNUMBER(SEARCH("34C",AB:AB)),"34C",
IF(ISNUMBER(SEARCH("34D",AB:AB)),"34D",
IF(ISNUMBER(SEARCH("36B",AB:AB)),"36B",
IF(ISNUMBER(SEARCH("36C",AB:AB)),"36C",
"LRG")))))))))))

// Size Code --> Size

=IF(ISNUMBER(SEARCH("XSM",N:N)),"XS",
IF(ISNUMBER(SEARCH("SML",N:N)),"S",
IF(ISNUMBER(SEARCH("MED",N:N)),"M",
IF(ISNUMBER(SEARCH("LRG",N:N)),"L",
IF(ISNUMBER(SEARCH("XLG",N:N)),"XL",
RIGHT(N6,3))))))