// Size --> Size Code

=IF(ISNUMBER(SEARCH("XS",AF:AF)),"XSM",
IF(ISNUMBER(SEARCH("S",AF:AF)),"SML",
IF(ISNUMBER(SEARCH("M",AF:AF)),"MED",
IF(ISNUMBER(SEARCH("XL",AF:AF)),"XLG",
IF(ISNUMBER(SEARCH("32B",AF:AF)),"32B",
IF(ISNUMBER(SEARCH("34A",AF:AF)),"34A",
IF(ISNUMBER(SEARCH("34B",AF:AF)),"34B",
IF(ISNUMBER(SEARCH("34C",AF:AF)),"34C",
IF(ISNUMBER(SEARCH("34D",AF:AF)),"34D",
IF(ISNUMBER(SEARCH("36B",AF:AF)),"36B",
IF(ISNUMBER(SEARCH("36C",AF:AF)),"36C",
"LRG")))))))))))

// Size Code --> Size

=IF(ISNUMBER(SEARCH("XSM",N:N)),"XS",
IF(ISNUMBER(SEARCH("SML",N:N)),"S",
IF(ISNUMBER(SEARCH("MED",N:N)),"M",
IF(ISNUMBER(SEARCH("LRG",N:N)),"L",
IF(ISNUMBER(SEARCH("XLG",N:N)),"XL",
RIGHT(N6,3))))))