=IF(ISNUMBER(SEARCH(1048, AA:AA)), "INNO KNITS, LLC",
IF(ISNUMBER(SEARCH(1049, AA:AA)), "INNO KNITS, LLC",
IF(ISNUMBER(SEARCH(1050, AA:AA)), "INNO KNITS, LLC",
IF(ISNUMBER(SEARCH(1058, AA:AA)), "INNO KNITS, LLC",
"BELAVIS CORP."))))